version: "3.7"
services:

    sales-api:
        build:
            context: sales-api
            dockerfile: Dockerfile
        volumes:
            - ./sales-api/code:/var/www/html

    service-mysql:
        volumes:
            - service-mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    service-mysql-volume:
        driver: local
